### ISSUE TITLE
Cannot import `journal` before `pyre`

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#99]
Occurs on v1.12.0 tag and main branch:

<details>

```
$ python3 -c 'import journal'
Traceback (most recent call last):
  File "/nix/store/9hqv2k2wim2qw3ws7y2jsjxgkz21na88-pyre-1.12.0/lib/python3.10/site-packages/pyre/h5/__init__.py", line 12, in <module>
    from . import disktypes
  File "/nix/store/9hqv2k2wim2qw3ws7y2jsjxgkz21na88-pyre-1.12.0/lib/python3.10/site-packages/pyre/h5/disktypes/__init__.py", line 11, in <module>
    type = pyre.libh5.datatypes.DataType
AttributeError: 'NoneType' object has no attribute 'datatypes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/9hqv2k2wim2qw3ws7y2jsjxgkz21na88-pyre-1.12.0/lib/python3.10/site-packages/journal/__init__.py", line 11, in <module>
    from . import exceptions
  File "/nix/store/9hqv2k2wim2qw3ws7y2jsjxgkz21na88-pyre-1.12.0/lib/python3.10/site-packages/journal/exceptions.py", line 8, in <module>
    from pyre.framework.exceptions import PyreError
  File "/nix/store/9hqv2k2wim2qw3ws7y2jsjxgkz21na88-pyre-1.12.0/lib/python3.10/site-packages/pyre/__init__.py", line 269, in <module>
    from . import h5
  File "/nix/store/9hqv2k2wim2qw3ws7y2jsjxgkz21na88-pyre-1.12.0/lib/python3.10/site-packages/pyre/h5/__init__.py", line 24, in <module>
    channel = journal.warning("pyre.h5")
AttributeError: partially initialized module 'journal' has no attribute 'warning' (most likely due to a circular import)
$ 
```

</details>

Bisected to 017a506199af3c47f26cddd503c339611d971015

**Comment by aivazis** [comment]
This has the same underlying cause as #89

**Comment by aivazis** [comment]
For the record, here is partial analysis of what's going on:

This case triggers this problem because you don't have `h5` bindings, which `pyre` now imports rather aggressively, something that should also be fixed. `pyre` then tries to issue a warning using `journal`. If `pyre` is imported first, `journal` gets a chance to get initialized correctly, and things work as expected. If `journal` is imported before `pyre`, the warning finds `journal` in partly initialized state and fails.
